---
title: "K3 article"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
library(ggplot2)
library(testthat)
```

## Preparation

```{r}
get_verdict <- function(p_value, alpha) {
  if (p_value < alpha) {
    return ("Different distributions")
  }
  "Same distributions"
}
```

```{r}
t <- wilcox.test(
  x = seq(from = 1, to = 10, length.out = 10),
  y = seq(from = 1, to = 10, length.out = 20), 
  alternative = "two.sided"
)
expect_equal(
  get_verdict(p_value = t$p.value, alpha = 0.05),
  "Same distributions"
)
```

```{r}
t <- wilcox.test(
  x = seq(from = 1, to = 5, length.out = 10),
  y = seq(from = 5, to = 10, length.out = 20), 
  alternative = "two.sided"
)
expect_equal(
  get_verdict(p_value = t$p.value, alpha = 0.05),
  "Different distributions"
)
```

## Data

```{r}
get_formation <- function(filename) {
  testthat::expect_true(file.exists(filename))
  text <- readLines(filename, warn = FALSE)
  is_found_indices <- stringr::str_detect(text, pattern = "Formation:.*")
  if (sum(is_found_indices) == 0) return("Not found")
  if (sum(is_found_indices) == 2) return("Found twice")
  formation_text <- text[is_found_indices]
  formation <- stringr::str_match(string = formation_text, pattern = "KKK|JKK|HKM")[1,1]
  if (is.na(formation)) return("Unknown formation")
  formation
  
}
expect_equal(
  "KKK", get_formation("K3Reviews/reviews/FransLiedje.md")
)
expect_equal(
  "JKK", 
  get_formation("K3Reviews/reviews/EnIkDans.md")
)
expect_equal(
  "HKM", 
  get_formation("K3Reviews/reviews/10000Luchtballonnen.md")
)
```

```{r}
get_rating <- function(name, filename) {
  testthat::expect_true(file.exists(filename))
  text <- readLines(filename, warn = FALSE)
  is_found_indices <- stringr::str_detect(text, pattern = paste0(name, "'s rating:.*"))
  if (sum(is_found_indices) == 0) return("Not found")
  if (sum(is_found_indices) == 2) return("Found twice")
  rating_text <- text[is_found_indices]
  rating <- stringr::str_match(
    string = rating_text, 
    pattern = paste0(name, "'s rating: (..?).10")
  )[1,2]
  if (is.na(rating)) return("Unknown rating")
  if (rating == "?") return("No rating")
  as.numeric(rating)
}
expect_equal(
  8, get_rating("Richel", "K3Reviews/reviews/FransLiedje.md")
)
expect_equal(
  9, 
  get_rating("Richel", "K3Reviews/reviews/EnIkDans.md")
)
expect_equal(
  "No rating", 
  get_rating("Richel", "K3Reviews/reviews/PuppyLove.md")
)
expect_equal(
  "No rating", 
  get_rating("Richel", "K3Reviews/reviews/AlleBabys.md")
)
```


```{r}
get_richels_rating <- function(filename) {
  get_rating(name = "Richel", filename = filename)
}
expect_equal(
  8, get_richels_rating("K3Reviews/reviews/FransLiedje.md")
)
expect_equal(
  9, 
  get_richels_rating("K3Reviews/reviews/EnIkDans.md")
)
expect_equal(
  "No rating", 
  get_richels_rating(filename = "K3Reviews/reviews/PuppyLove.md")
)
```

```{r}
get_marks_rating <- function(filename) {
  get_rating("Mark", filename)
}
expect_equal(
  6, get_marks_rating(filename = "K3Reviews/reviews/Beroemd.md")
)
expect_equal(
  0, 
  get_marks_rating("K3Reviews/reviews/EyaHoya.md")
)
```

```{r}
get_formations <- function(filenames) {
  testthat::expect_true(all(file.exists(filenames)))
  formations <- rep("", length(filenames))
  for (i in seq_along(filenames)) {
    formations[i] <- get_formation(filenames[i])
  }
  formations
}
```

```{r}
get_richels_ratings <- function(filenames) {
  testthat::expect_true(all(file.exists(filenames)))
  richels_ratings <- rep(0, length(filenames))
  for (i in seq_along(filenames)) {
    richels_ratings[i] <- get_richels_rating(filenames[i])
  }
  richels_ratings
}
```

```{r}
get_marks_ratings <- function(filenames) {
  testthat::expect_true(all(file.exists(filenames)))
  marks_ratings <- rep(0, length(filenames))
  for (i in seq_along(filenames)) {
    marks_ratings[i] <- get_marks_rating(filenames[i])
  }
  marks_ratings
}
```


```{r}
get_ratings <- function(filenames) {
  df_richel <- data.frame(
    filename = filenames, 
    formation = get_formations(filenames),
    rating = get_richels_ratings(filenames),
    reviewer = "Richel"
  )
  df_mark <- data.frame(
    filename = filenames, 
    formation = get_formations(filenames),
    rating = get_marks_ratings(filenames),
    reviewer = "Mark"
  )
  df <- rbind(df_richel, df_mark)
  df$filename <- as.character(df$filename)
  df$rating <- as.character(df$rating)
  df$formation <- as.character(df$formation)
  df$reviewer <- as.factor(df$reviewer)
  df
}
filenames <- c(
  "K3Reviews/reviews/FransLiedje.md",
  "K3Reviews/reviews/EnIkDans.md",
  "K3Reviews/reviews/Beroemd.md",
  "K3Reviews/reviews/EyaHoya.md"
)
df <- get_ratings(filenames)
expect_equal(nrow(df), 8)
```

```{r}
filenames <- list.files(path = "K3Reviews/reviews", pattern = "*.md", full.names = TRUE)
df <- get_ratings(filenames)
```

Plots:

```{r}
ggplot(df, aes(x = formation)) +
  geom_histogram(stat = "count") +
  ggsave("formations.png", width = 7, height = 7)
```

```{r}
df_valid <- df
df_valid$rating <- as.numeric(df$rating)
df_valid <- na.omit(df_valid)
df_valid <- df_valid[ nchar(df_valid$formation) == 3, ]


ggplot(df_valid, aes(x = reviewer , y = rating)) +
  geom_boxplot() +
  ggsave("ratings_per_reviewer.png", width = 7, height = 7)
```

```{r}
ggplot(df_valid, aes(x = formation , y = rating)) +
  geom_boxplot() +
  ggsave("ratings_per_formation.png", width = 7, height = 7)
```

```{r}
ggplot(df_valid, aes(x = formation , y = rating, fill = reviewer)) +
  geom_boxplot() +
  ggsave("ratings_per_formation_per_reviewer.png", width = 7, height = 7)
```

Real data:

```{r}
set.seed(42)

ratings_1 <- df_valid[df_valid$formation == "KKK", ]$rating
ratings_2 <- df_valid[df_valid$formation == "HKM", ]$rating
```

## Stats

```{r}
alpha <- 0.05
```

```{r}
t <- wilcox.test(
  x = ratings_1, 
  y = ratings_2, 
  alternative = "two.sided"
)
m <- matrix(
  data = c(
    "p_value", t$p.value,
    "alternative", t$alternative,
    "method", t$method,
    "data.name", t$data.name,
    "verdict", get_verdict(p_value = t$p.value, alpha = alpha)
  ),
  ncol = 2,
  byrow = TRUE
)
colnames(m) <- c("parameter", "value")
df <- tibble::as_tibble(m)
names(df) <- c("parameter", "value")
write.csv(df, "stats.csv", row.names = FALSE)
knitr::kable(df)
```

## Plot

```{r}
df <- tibble::tibble(
  formation = c(
    rep(1, length(ratings_1)), 
    rep(2, length(ratings_2))
  ),
  rating = c(ratings_1, ratings_2)
)
df$formation <- as.factor(df$formation)
ggplot(df, aes(x = formation, y = rating)) + 
  geom_boxplot() +
  scale_y_continuous(
    limits = c(1, 10), 
    breaks = seq(1, 10)
  ) +
  ggsave("figure_1.png", width = 7, height = 7)
```

